### PR TITLE
Add a note to encoding guidance about table order in brotli patches.

### PR DESCRIPTION
**Pull request by garretrieger**
For #183

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/185.html" title="Last updated on Jun 18, 2024, 6:23 PM UTC (2894d16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/185/0f7eb6e...2894d16.html" title="Last updated on Jun 18, 2024, 6:23 PM UTC (2894d16)">Diff</a>

### CODE REVIEW

**Review by skef — COMMENTED** [review]
Can we expand this section to include the WOFF2 encoding of the initial font file or would that information belong somewhere else?

**Comment by garretrieger** [comment]
> Can we expand this section to include the WOFF2 encoding of the initial font file or would that information belong somewhere else?

No problem, I'll add that. Should be fine to add it to this subsection.

**Comment by garretrieger** [comment]
> > Can we expand this section to include the WOFF2 encoding of the initial font file or would that information belong somewhere else?
> 
> No problem, I'll add that. Should be fine to add it to this subsection.

Done, section has been updated.

**Review by skef — APPROVED** [review]
LGTM

**Pull request merged**
