### PR TITLE
Split off the range request section back into a separate document.

### PR DESCRIPTION
**Pull request by garretrieger**
This will allow the patch subset specification to be advanced without range request being complete.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/138.html" title="Last updated on Mar 13, 2023, 9:49 PM UTC (62e7c51)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/138/b9697c9...62e7c51.html" title="Last updated on Mar 13, 2023, 9:49 PM UTC (62e7c51)">Diff</a>

### CODE REVIEW

**Review by svgeesus — CHANGES_REQUESTED** [review]
One typo, otherwise looks good

**Review by vlevantovsky — COMMENTED** [review]
LGTM

**Comment by skef** [comment]
I suggest holding off on this for the time being.

**Comment by skef** [comment]
More specifically: I'm currently thinking we would be better ending up with either a single document or three documents. There's enough material (background, definitions, comparing the options) common to both that two seems like the wrong number. 

Of course, this is partly based on the prospects for replacing the range-request content with other related content.

**Comment by svgeesus** [comment]
> What's the typo?

Thought I had added it as a review comment. And now can't see it. Nevermind.

**Review by svgeesus — APPROVED** [review]

**Comment by skef** [comment]
> I would much rather merge this split, republish the documents, and start TAG review.

Start TAG review of both documents, or just the patch-subset spec? Do you think the range-request spec is ready to be reviewed?

**Comment by skef** [comment]
I guess I have no inherent objections as long as substantial changes to the range-request spec (including almost complete replacement) and any further potential rearrangement (including re-integration of the specs, if desired) are still possible after the merge.

**Comment by skef** [comment]
> In this regard, the range-request changes and future re-integration of a separate document, would definitely be something that is both possible and desirable.

In that case I withdraw any objections to merging this.

**Pull request merged**
