### PR TITLE
Suggested reorg edits and additions

### PR DESCRIPTION
**Pull request by skef**
Some suggestions and additions for #171 . Note that this PR is against `reorg` rather than `main`. Seemed easiest to have the conversation this way.

***
<a href="https://pr-preview.s3.amazonaws.com/skef/IFT/pull/172.html" title="Last updated on Apr 30, 2024, 12:22 AM UTC (1981855)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/172/e81b57e...skef:1981855.html" title="Last updated on Apr 30, 2024, 12:22 AM UTC (1981855)">Diff</a>

### CODE REVIEW

**Comment by skef** [comment]
Because it's against `reorg` I didn't rebuild Overview.html.

**Comment by skef** [comment]
I was wondering about the w3c stance on things like "behaviour" and found https://www.w3.org/Guide/manual-of-style/#Spelling

**Comment by garretrieger** [comment]
This looks good to me. If you want I can pull this commit into my PR and also address some of the TODO's that you are adding. Does that work for you?

**Comment by skef** [comment]
Yes, that sounds good. And of course don't feel obligated to take everything verbatim, this was just comments in PR form.

**Pull request merged**
